### ISSUE TITLE
taiyのローカル環境でMisskeyを建てたい

### ISSUE THREAD

**Issue by taiyme** [taiyme/misskey#42]
## Summary

たすけてください、ひどい環境で働かされています

**Comment by cffnpwr** [comment]
# 事前準備

```sh
cp .config/docker_example.yml .config/default.yml
cp .config/docker_example.env .config/docker.env
```

`default.yml`と`docker.env`(dockerを使う場合)をコピーして適当な設定をする。
このとき、`default.yml`のURLは`http://localhost:3000/`に設定する。(ポートが異なる場合は3000以外にする)

# 開発環境の起動

## dockerを使う場合

以下のコマンドで起動
```sh
docker compose -f docker-compose.dev.yml up -d --build
```

以下のコマンドで内部のシェルに入れる
VSCodeを使用している場合は左下のあずきゃマーク(><)からReopen in containerでコンテナ内に入れる
```sh
docker compose -f docker-compose.dev.yml exec -it web bash
```

## dockerを使わない場合

ローカルにpostgresとredisを立てる

pnpmの有効化
```sh
corepack enable
```

# misskey開発環境の起動

依存関係のインストール
```sh
pnpm i
```

DBの初期化
```sh
pnpm migrate
```

misskey開発環境の起動
```sh
pnpm dev
```

少し待つとmisskeyが起動するので`http://localhost:3000`にアクセスして表示されれば完了。

**Comment by adzukyat** [comment]
DBとRedisだけDocker上で動かす方法もあって、やり方は

- docker-compose.ymlのservicesからwebをコメントアウト
- dbとredisのnetworksにexternal_networkを追加
- dbとredisにportsを追加して、dbには”5432:5432”を、redisには”6379:6379”を設定

こんな感じになってればOK

```yml
services:
  redis:
    …
    networks:
      - internal_network
      - external_network
    ports:
      - "6379:6379"
    …

  db:
    …
    networks:
      - internal_network
      - external_network
    ports:
      - "5432:5432"
    …
```

全部Dockerで動かす方法と比べてMisskey側のパフォーマンスが劣化しないからビルドが速くなるはず

**Comment by melt-adzuki** [comment]
DBとRedisだけDocker上で動かす方法もあって、やり方は

- docker-compose.ymlのservicesからwebをコメントアウト
- dbとredisのnetworksにexternal_networkを追加
- dbとredisにportsを追加して、dbには”5432:5432”を、redisには”6379:6379”を設定

こんな感じになってればOK

```yml
services:
  redis:
    …
    networks:
      - internal_network
      - external_network
    ports:
      - "6379:6379"
    …

  db:
    …
    networks:
      - internal_network
      - external_network
    ports:
      - "5432:5432"
    …
```

全部Dockerで動かす方法と比べてMisskey側のパフォーマンスが劣化しないからビルドが速くなるはず

**Comment by cffnpwr** [comment]
DBとRedisだけdockerで動かす方法も書こうと思ったけど面倒だったから
>ローカルにpostgresとredisを立てる

で済ませてしまった

**Comment by cffnpwr** [comment]
こんな感じでそもそもNetworksを消しても良い
```yaml
version: "3"

services:
  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  db:
    restart: always
    image: postgres:12.2-alpine
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```
